<a href="https://colab.research.google.com/github/MuhammadFarrasThohari/Desain-dan-Analisis-Algoritma/blob/master/Latihan_Pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LATIHAN PERTEMUAN 3

In [ ]:
import datetime

In [ ]:
z = str(datetime.date.today())


In [ ]:
x = datetime.datetime.today()
y = (x.strftime("%B %d %Y"))

In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
Mahasiswa = ["Muhammad Farras Thohari Ramadhan", "2022071063", "Informatika", "Desain dan Analisis Algoritma", z, "UPJ"]
print(Mahasiswa)

['Muhammad Farras Thohari Ramadhan', '2022071063', 'Informatika', 'Desain dan Analisis Algoritma', '2023-09-11', 'UPJ']


In [ ]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
print(bin_colors)

['Red', 'Green', 'Blue', 'Yellow']


In [ ]:
#Latihan mencetak list menggunakan Index
print(Mahasiswa[1])
print(Mahasiswa[5])

2022071063
UPJ


In [ ]:
#Latihan Slicing Index
print(bin_colors[0:2])
print(bin_colors[0:4])
print(bin_colors[2:])
print(bin_colors[:2])

['Red', 'Green']
['Red', 'Green', 'Blue', 'Yellow']
['Blue', 'Yellow']
['Red', 'Green']


In [ ]:
#Latihan mencetak ist mahasiswa menggunakan slicing
print(Mahasiswa[1:3])
print(Mahasiswa[1:2])
print(Mahasiswa[2:3])

[2022071063, 'Informatika']
[2022071063]
['Informatika']


In [ ]:
for aColor in bin_colors:
  print("Square " + aColor)

Square Red
Square Green
Square Blue
Square Yellow


In [ ]:
for aMahasiswa in Mahasiswa:
  print("UPJ " + aMahasiswa)

UPJ Muhammad Farras Thohari Ramadhan
UPJ 2022071063
UPJ Informatika
UPJ Desain dan Analisis Algoritma
UPJ 2023-09-11
UPJ UPJ


In [ ]:
#Tuple
bin_colors = ("Red", "Green", "Blue", "Yellow")
print(bin_colors[1])

Green


In [ ]:
#Latihan Tuple
UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [ ]:
#Latihan Nested Tuple
pertama = (100)
kedua = (200, 400, 600)
ketiga = (300)
keempat = (400, 800)
nested_tuple = (pertama, kedua, ketiga, keempat)
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [ ]:
#Dictionary
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refuse_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refuse_color': 'Red'}


In [ ]:
#Latihan Dictionary
dict_mahasiswa = {
    "Nama": "Muhammad Farras Thohari Ramadhan",
    "NIM": "2022071063",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(dict_mahasiswa)

{'Nama': 'Muhammad Farras Thohari Ramadhan', 'NIM': '2022071063', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
#Set
set_01 = {1,4,5,6,2}
print(set_01)

{1, 2, 4, 5, 6}


In [ ]:
#Latihan set
red = {"leaves", "fire hydrant", "blood"}
yellow = {"leaves", "fire hydrant", "rose", "dandelion"}

print(yellow|red)
print(yellow&red)

{'rose', 'dandelion', 'fire hydrant', 'leaves', 'blood'}
{'fire hydrant', 'leaves'}


In [ ]:
#Data Frame
import pandas as pd
df = pd.DataFrame([
    [1, "Fares", 32, True],
    [2, "Elena", 23, False],
    [3, "Steven", 40, True]]
    )

print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [ ]:
#Latihan Data Frame
data = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10],
])
data.columns = ["No", "Prodi", "Mahasiswa", "Laki-Laki", "Perempuan"]
print(data)

   No             Prodi  Mahasiswa  Laki-Laki  Perempuan
0   1       Informatika         50         30         20
1   2  Sistem Informasi         55         30         25
2   3      Teknik Sipil         40         30         10


In [ ]:
#Matrix
import numpy as np
my_matrix = np.array([[11,12,13], [21,22,23], [31,32,33]])
print(my_matrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
#Latihan Matrix
Matrix = np.array([[100,200,300], [700,600,500], [900, 1000, 800]])
print(np.transpose(Matrix))

[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
